language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-places365-cnn .
  - docker run -it -d -p 5000:5000 max-places365-cnn

before_script:
  - pip install pytest requests

script:
  - pytest tests/test.py
